# Generated by Django 5.2.6 on 2025-09-26 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0003_cidade_dia_da_semana_especialidade_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='opnioes',
            field=models.TextField(null=True, verbose_name='Opniões'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='Telefone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='dia_da_semana',
            field=models.ManyToManyField(related_name='Dia_da_Semana', to='medicSearch.dia_da_semana'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='horario_de_abertura',
            field=models.TimeField(verbose_name='Horário de abertura'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='horario_de_fechamento',
            field=models.TimeField(verbose_name='Horário de fechamento'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='whatsapp',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='endereco',
            field=models.ManyToManyField(related_name='Endereço', to='medicSearch.endereco', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='especialidade',
            field=models.ManyToManyField(related_name='Especialidade', to='medicSearch.especialidade', verbose_name='Especialidade'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='favoritos',
            field=models.ManyToManyField(related_name='favoritos', to=settings.AUTH_USER_MODEL, verbose_name='Favoritos'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nascimento',
            field=models.DateField(default=None, null=True, verbose_name='Nascimento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
