# Generated by Django 5.2.6 on 2025-09-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0004_alter_avaliacao_opnioes_alter_endereco_telefone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dia_da_semana',
            name='nome',
        ),
        migrations.AddField(
            model_name='dia_da_semana',
            name='data',
            field=models.DateField(default=None, null=True, verbose_name='Data'),
        ),
    ]
