# Generated by Django 5.2.6 on 2025-09-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0005_remove_dia_da_semana_nome_dia_da_semana_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
